title: Pavel's Site
description: > # this means to ignore newlines until "baseurl:"
  A place for things I write and projects I've worked on
baseurl: "" # the subpath of your site, e.g. /blog
url: "pavelkomarov.github.io" # the base hostname & protocol for your site
# Build settings

logo: "../css/2016_style/img/icon-large.png"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2016_pages', '_2017_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/hewhoiscalledpavel
  - title: github
    url: https://github.com/pavelkomarov
  - title: linkedin
    url: https://linkedin.com/pub/pavel-komarov/48/340/a28
  - title: instagram
    url: https://www.instagram.com/skinny_ape/
  - title: stack-overflow
    url: https://stackoverflow.com/users/story/2084503

# Build settings
markdown: kramdown
permalink: pretty