title: Pavel's Site
description: > # this means to ignore newlines until "baseurl:"
  A place for things I write and projects I've worked on
baseurl: "" # the subpath of your site, e.g. /blog
url: "pavelkomarov.github.io" # the base hostname & protocol for your site
# Build settings

google_site_verification: googleXXXXXXXXXXXXXXXX.html

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Build settings
markdown: kramdown
permalink: pretty

# Site data below, because I don't want a whole /_data/template.yml file to access only these few things.
# Variables defined here are accessible via {{ site.color.secondary }}, for example.

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - icon: fab fa-facebook
    url: https://www.facebook.com/hewhoiscalledpavel
  - icon: fab fa-github
    url: https://github.com/pavelkomarov
  - icon: fab fa-linkedin
    url: https://linkedin.com/pub/pavel-komarov/48/340/a28
  - icon: fab fa-instagram
    url: https://www.instagram.com/skinny_ape/
  - icon: fab fa-stack-overflow
    url: https://stackoverflow.com/users/story/2084503
  - icon: fa fa-envelope
    url: mailto:pvlkmrv@gmail.com
  - icon: fa fa-file
    url: https://www.dropbox.com/s/9ngmmye4pu2kjj9/Resume%20abridged%202017.8.30.pdf?dl=0
  - icon: fab fa-flipboard
    url: https://flipboard.com/@pavel_komarov/pavel%27s-favorites-78tpvu6pz

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 3cb371
  secondary: 6ecf99
  secondary-dark: 00283c
  muted: 777

# Font Families
font:
  primary: 'Montserrat, "Helvetica Neue",Helvetica,Arial,sans-serif'
  secondary: '"Droid Serif", "Helvetica Neue", Helvetica,Arial,sans-serif'
