title: Pavel's Site
description: > # this means to ignore newlines until "baseurl:"
  A place for things I write and projects I've worked on
baseurl: "" # the subpath of your site, e.g. /blog
url: "pavelkomarov.github.io" # the base hostname & protocol for your site
# Build settings

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - icon: fab fa-facebook
    url: https://www.facebook.com/hewhoiscalledpavel
  - icon: fab fa-github
    url: https://github.com/pavelkomarov
  - icon: fab fa-linkedin
    url: https://linkedin.com/pub/pavel-komarov/48/340/a28
  - icon: fab fa-instagram
    url: https://www.instagram.com/skinny_ape/
  - icon: fab fa-stack-overflow
    url: https://stackoverflow.com/users/story/2084503
  - icon: fa fa-envelope
    url: mailto:pvlkmrv@gmail.com
  - icon: fa fa-file
    url: https://www.dropbox.com/s/9ngmmye4pu2kjj9/Resume%20abridged%202017.8.30.pdf?dl=0
  - icon: fab fa-flipboard
    url: https://flipboard.com/@pavel_komarov/pavel%27s-favorites-78tpvu6pz

# Build settings
markdown: kramdown
permalink: pretty
sass:
  sass_dir: theme/_sass